pod 'pop', '~> 1.0'
pod 'Colours'
pod 'CRToast', '~> 0.0.7'
pod 'FontAwesomeKit', '~> 2.1.0'
pod 'LiveFrost'
pod 'XLForm', '~> 1.0.0'
pod 'SBJson', '~> 4.0.0'
pod 'ImageInformationForm', :git => 'https://github.com/forsythetony/infoForm.git'
