pod 'pop', '~> 1.0'
pod 'Masonry'
pod 'ChameleonFramework'
pod 'Colours', :git => 'https://github.com/forsythetony/Colours.git'
pod 'CRToast', '~> 0.0.7'
pod 'FontAwesomeKit', '~> 2.1.0'
pod 'LiveFrost'
pod 'SBJson', '~> 4.0.0'
pod 'ImageTaker', :git => 'https://github.com/forsythetony/ImageTaker.git'
pod 'VBFPopFlatButton'
pod 'SDWebImage', '~>3.6'
